### PR TITLE
Create sing-a-song.md

### PR DESCRIPTION
**Pull request by octocat**
Lalala.

### CODE REVIEW

**Review by Kookoorooza — CHANGES_REQUESTED** [review]
Can this line show instead of tell?

**Review by jmarlena — APPROVED** [review]
This looks good to me.

**Comment by RodrigoMDillanes** [comment]
heyy teach me how can i do this in R!!

**Comment by octocat** [comment]
Let's close this PR for now.

**Review by dennisundmax3-wq — COMMENTED** [review]
Fgg

**Pull request closed without merging**
